### ISSUE TITLE
Handshake failure while running backend

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_backend#77]
when backend server is running and we rebooted a device and after the device is ready if we trigger the discovery from the UI the backend will result in bello error 

`Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`

**Comment by vivek-metricdust** [comment]
logs for debugging 
`[2024-10-16 11:51:07,821][INFO][gnmi_sub.py:427][Thread-11 (process_request_thread)] Subscribing for 10.10.229.111
Exception in thread subscription_thread_10.10.229.111:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vivek/.cache/pypoetry/virtualenvs/orca-backend--VtnSJ0g-py3.10/lib/python3.10/site-packages/orca_nw_lib/gnmi_sub.py", line 289, in handle_update
    for resp in device_gnmi_stub.Subscribe(subscribe_to_path(sub_req)):
  File "/home/vivek/.cache/pypoetry/virtualenvs/orca-backend--VtnSJ0g-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/vivek/.cache/pypoetry/virtualenvs/orca-backend--VtnSJ0g-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 952, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.10.229.111:8080: Ssl handshake failed (TSI_PROTOCOL_FAILURE): SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-16T11:51:07.825682458+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.10.229.111:8080: Ssl handshake failed (TSI_PROTOCOL_FAILURE): SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"}"
>`

**Comment by rahul-1475** [comment]
- This bug has been fixed in in issue #68
